server:
  port: 9001

eureka:
  client:
    register-wth-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

#spring:
#  application:
#    name: DEPARTMENT-SERVICE
#  cloud:
#    config:
#      enabled: true
#      uri: http://localhost:9296

#  zipkin:
#    base-url: http://127.0.0.1:9411/